.\" termin.al-name: about
.\" termin.al-usage: about
.\" termin.al-summary: Open about content.
.TH ABOUT 1 "" "termin.al" "termin.al Manual"
.ftr B R
.ftr I R
.ftr BI R
.SH NAME
about \- Open about content.
.SH SYNOPSIS
.nf
about
.fi
.SH DESCRIPTION
Opens the published about document in the inline viewer.
.SH EXAMPLES
.nf
$ about
.fi
.SH SEE ALSO
help(1), man(1)
