.\" termin.al-name: clear
.\" termin.al-usage: clear
.\" termin.al-summary: Clear terminal scrollback.
.TH CLEAR 1 "" "termin.al" "termin.al Manual"
.ftr B R
.ftr I R
.ftr BI R
.SH NAME
clear \- Clear terminal scrollback.
.SH SYNOPSIS
.nf
clear
.fi
.SH DESCRIPTION
Removes terminal scrollback from the current shell pane. Command history and the pane's working directory are preserved.
.SH EXAMPLES
.nf
$ clear
.fi
.SH SEE ALSO
help(1), man(1)
