.\" termin.al-name: notes
.\" termin.al-usage: notes
.\" termin.al-summary: Open notes content.
.TH NOTES 1 "" "termin.al" "termin.al Manual"
.ftr B R
.ftr I R
.ftr BI R
.SH NAME
notes \- Open notes content.
.SH SYNOPSIS
.nf
notes
.fi
.SH DESCRIPTION
Opens the published notes collection for keyboard or touch navigation.
.SH EXAMPLES
.nf
$ notes
.fi
.SH SEE ALSO
help(1), man(1)
