.\" termin.al-name: pwd
.\" termin.al-usage: pwd
.\" termin.al-summary: Print this shell pane's virtual directory.
.TH PWD 1 "" "termin.al" "termin.al Manual"
.ftr B R
.ftr I R
.ftr BI R
.SH NAME
pwd \- Print this shell pane's virtual directory.
.SH SYNOPSIS
.nf
pwd
.fi
.SH DESCRIPTION
Prints the virtual working directory of the current shell pane using termin.al path notation.
.SH EXAMPLES
.nf
$ pwd
.fi
.SH SEE ALSO
help(1), man(1)
