.\" termin.al-name: tools
.\" termin.al-usage: tools
.\" termin.al-summary: Open tools content.
.TH TOOLS 1 "" "termin.al" "termin.al Manual"
.ftr B R
.ftr I R
.ftr BI R
.SH NAME
tools \- Open tools content.
.SH SYNOPSIS
.nf
tools
.fi
.SH DESCRIPTION
Opens the published tools document in the inline viewer.
.SH EXAMPLES
.nf
$ tools
.fi
.SH SEE ALSO
help(1), man(1)
